window.PHOTO_STYLES_DATA = [
  { "id": "portrait-natural-light", "ko": "자연광 인물", "en": "Natural Light Portrait", "q": "natural light portrait photography" },
  { "id": "portrait-studio", "ko": "스튜디오 인물", "en": "Studio Portrait", "q": "studio portrait lighting" },
  { "id": "beauty-lighting", "ko": "뷰티 라이팅", "en": "Beauty Lighting", "q": "beauty lighting portrait" },
  { "id": "high-key", "ko": "하이키", "en": "High Key", "q": "high key lighting photography" },
  { "id": "low-key", "ko": "로우키", "en": "Low Key", "q": "low key lighting photography" },
  { "id": "rembrandt-lighting", "ko": "렘브란트 라이팅", "en": "Rembrandt Lighting", "q": "Rembrandt lighting portrait" },
  { "id": "split-lighting", "ko": "스플릿 라이팅", "en": "Split Lighting", "q": "split lighting portrait" },
  { "id": "loop-lighting", "ko": "루프 라이팅", "en": "Loop Lighting", "q": "loop lighting portrait" },
  { "id": "butterfly-lighting", "ko": "버터플라이 라이팅", "en": "Butterfly Lighting", "q": "butterfly lighting portrait" },
  { "id": "clamshell-lighting", "ko": "클램쉘 라이팅", "en": "Clamshell Lighting", "q": "clamshell lighting portrait" },
  { "id": "rim-light", "ko": "림 라이트", "en": "Rim Light", "q": "rim lighting portrait" },
  { "id": "backlit", "ko": "역광", "en": "Backlit", "q": "backlit portrait photography" },
  { "id": "silhouette", "ko": "실루엣", "en": "Silhouette", "q": "silhouette photography" },
  { "id": "chiaroscuro", "ko": "키아로스쿠로", "en": "Chiaroscuro", "q": "chiaroscuro photography lighting" },
  { "id": "cinematic-lighting", "ko": "시네마틱 라이팅", "en": "Cinematic Lighting", "q": "cinematic lighting photography" },
  { "id": "moody-portrait", "ko": "무디 인물", "en": "Moody Portrait", "q": "moody portrait photography" },
  { "id": "noir-lighting", "ko": "느와르", "en": "Noir", "q": "film noir lighting photography" },
  { "id": "neon-night", "ko": "네온 나이트", "en": "Neon Night", "q": "neon night street photography" },
  { "id": "golden-hour", "ko": "골든아워", "en": "Golden Hour", "q": "golden hour photography" },
  { "id": "blue-hour", "ko": "블루아워", "en": "Blue Hour", "q": "blue hour photography" },
  { "id": "overcast-soft", "ko": "흐림/소프트 라이트", "en": "Overcast Soft Light", "q": "overcast soft light photography" },
  { "id": "hard-sun", "ko": "하드 선라이트", "en": "Hard Sunlight", "q": "hard sunlight portrait photography" },
  { "id": "window-light", "ko": "창문광", "en": "Window Light", "q": "window light portrait" },
  { "id": "tungsten-warm", "ko": "텅스텐 웜 톤", "en": "Tungsten Warm", "q": "tungsten lighting photography" },
  { "id": "gel-lighting", "ko": "젤 컬러 라이팅", "en": "Gel Lighting", "q": "gel lighting portrait" },
  { "id": "two-tone-gel", "ko": "투톤 젤", "en": "Two-tone Gel", "q": "two color gel lighting portrait" },
  { "id": "ring-light", "ko": "링 라이트", "en": "Ring Light", "q": "ring light portrait photography" },
  { "id": "softbox", "ko": "소프트박스", "en": "Softbox", "q": "softbox portrait lighting" },
  { "id": "octabox", "ko": "옥타박스", "en": "Octabox", "q": "Photo studio equipment octabox" },
  { "id": "umbrella-lighting", "ko": "엄브렐라 라이팅", "en": "Umbrella Lighting", "q": "umbrella lighting portrait" },
  { "id": "three-point", "ko": "3점 조명", "en": "Three-point Lighting", "q": "three point lighting photography" },
  { "id": "product-studio", "ko": "제품 스튜디오", "en": "Product Studio", "q": "product photography studio lighting" },
  { "id": "product-highkey", "ko": "제품 하이키", "en": "High Key Product", "q": "high key product photography" },
  { "id": "product-lowkey", "ko": "제품 로우키", "en": "Low Key Product", "q": "low key product photography" },
  { "id": "food-natural", "ko": "푸드 자연광", "en": "Natural Light Food", "q": "natural light food photography" },
  { "id": "food-moody", "ko": "무디 푸드", "en": "Moody Food", "q": "moody food photography" },
  { "id": "flatlay", "ko": "플랫레이", "en": "Flat Lay", "q": "flat lay photography" },
  { "id": "editorial-fashion", "ko": "에디토리얼 패션", "en": "Editorial Fashion", "q": "editorial fashion photography lighting" },
  { "id": "street-photography", "ko": "스트리트", "en": "Street Photography", "q": "street photography" },
  { "id": "documentary", "ko": "다큐멘터리", "en": "Documentary", "q": "documentary photography" },
  { "id": "lifestyle", "ko": "라이프스타일", "en": "Lifestyle", "q": "lifestyle photography natural light" },
  { "id": "wedding", "ko": "웨딩", "en": "Wedding", "q": "wedding photography style" },
  { "id": "sports-action", "ko": "스포츠 액션", "en": "Sports Action", "q": "sports action photography" },
  { "id": "wildlife", "ko": "야생동물", "en": "Wildlife", "q": "wildlife photography" },
  { "id": "macro", "ko": "매크로", "en": "Macro", "q": "macro photography" },
  { "id": "bokeh", "ko": "보케", "en": "Bokeh", "q": "bokeh photography" },
  { "id": "shallow-dof", "ko": "얕은 심도", "en": "Shallow Depth of Field", "q": "shallow depth of field portrait" },
  { "id": "deep-focus", "ko": "딥 포커스", "en": "Deep Focus", "q": "deep focus photography" },
  { "id": "long-exposure", "ko": "롱 익스포저", "en": "Long Exposure", "q": "long exposure photography" },
  { "id": "light-trails", "ko": "라이트 트레일", "en": "Light Trails", "q": "light trails long exposure" },
  { "id": "panning", "ko": "패닝", "en": "Panning", "q": "panning photography motion blur" },
  { "id": "motion-blur", "ko": "모션 블러", "en": "Motion Blur", "q": "motion blur photography" },
  { "id": "flash-street", "ko": "플래시 스트리트", "en": "On-camera Flash Street", "q": "on camera flash street photography" },
  { "id": "direct-flash", "ko": "다이렉트 플래시", "en": "Direct Flash", "q": "direct flash photography" },
  { "id": "bounce-flash", "ko": "바운스 플래시", "en": "Bounce Flash", "q": "bounce flash photography" },
  { "id": "hdr", "ko": "HDR", "en": "HDR", "q": "HDR photography" },
  { "id": "film-look", "ko": "필름 룩", "en": "Film Look", "q": "film look photography" },
  { "id": "kodachrome", "ko": "코다크롬", "en": "Kodachrome", "q": "Kodachrome color photography" },
  { "id": "portra", "ko": "포트라 톤", "en": "Portra Tone", "q": "Portra film look" },
  { "id": "fuji-provia", "ko": "후지 프로비아", "en": "Fuji Provia", "q": "Fujifilm Provia look" },
  { "id": "cinestill", "ko": "시네스틸", "en": "Cinestill", "q": "Cinestill film look" },
  { "id": "black-and-white", "ko": "흑백", "en": "Black and White", "q": "black and white photography" },
  { "id": "bw-high-contrast", "ko": "흑백 하이 콘트라스트", "en": "B&W High Contrast", "q": "high contrast black and white photography" },
  { "id": "bw-matte", "ko": "흑백 매트", "en": "B&W Matte", "q": "matte black and white photography" },
  { "id": "matte-color", "ko": "컬러 매트", "en": "Matte Color", "q": "matte color grading photography" },
  { "id": "teal-orange", "ko": "틸&오렌지", "en": "Teal & Orange", "q": "teal and orange color grading" },
  { "id": "pastel-tone", "ko": "파스텔 톤", "en": "Pastel Tone", "q": "pastel color grading photography" },
  { "id": "muted-tone", "ko": "뮤트 톤", "en": "Muted Tone", "q": "muted tones photography" },
  { "id": "vibrant-pop", "ko": "비비드 팝", "en": "Vibrant Pop", "q": "vibrant color photography" },
  { "id": "monochrome-color", "ko": "모노크롬 컬러", "en": "Monochrome Color", "q": "monochrome color photography" },
  { "id": "duotone", "ko": "듀오톤", "en": "Duotone", "q": "duotone photography" },
  { "id": "infrared", "ko": "적외선", "en": "Infrared", "q": "infrared photography" },
  { "id": "aerial-drone", "ko": "드론 항공", "en": "Aerial Drone", "q": "aerial drone photography" },
  { "id": "architecture", "ko": "건축", "en": "Architecture", "q": "architecture photography" },
  { "id": "interior", "ko": "인테리어", "en": "Interior", "q": "interior photography lighting" },
  { "id": "landscape", "ko": "풍경", "en": "Landscape", "q": "landscape photography" },
  { "id": "astrophotography", "ko": "천체사진", "en": "Astrophotography", "q": "astrophotography night sky" },
  { "id": "milky-way", "ko": "은하수", "en": "Milky Way", "q": "milky way astrophotography" },
  { "id": "minimal-architecture", "ko": "미니멀 건축", "en": "Minimal Architecture", "q": "minimal architecture photography" },
  { "id": "symmetry", "ko": "대칭", "en": "Symmetry", "q": "symmetry photography" },
  { "id": "negative-space", "ko": "네거티브 스페이스", "en": "Negative Space", "q": "negative space photography" },
  { "id": "reflections", "ko": "반사/리플렉션", "en": "Reflections", "q": "reflection photography" },
  { "id": "rainy-street", "ko": "비 오는 거리", "en": "Rainy Street", "q": "rainy street photography reflections" },
  { "id": "fog-mist", "ko": "안개/미스트", "en": "Fog & Mist", "q": "foggy photography" },
  { "id": "underwater", "ko": "수중", "en": "Underwater", "q": "underwater photography" },
  { "id": "backdrop-seamless", "ko": "심리스 배경", "en": "Seamless Backdrop", "q": "seamless backdrop photography" },
  { "id": "color-block-backdrop", "ko": "컬러 블록 배경", "en": "Color Block Backdrop", "q": "color backdrop portrait photography" },
  { "id": "hard-shadow", "ko": "하드 섀도우", "en": "Hard Shadow", "q": "hard shadows portrait photography" },
  { "id": "soft-shadow", "ko": "소프트 섀도우", "en": "Soft Shadow", "q": "soft shadow portrait photography" },
  { "id": "high-contrast-light", "ko": "하이 콘트라스트 라이팅", "en": "High Contrast Lighting", "q": "high contrast lighting photography" },
  { "id": "ambient-only", "ko": "앰비언트만", "en": "Ambient Only", "q": "ambient light photography" },
  { "id": "mixed-light", "ko": "믹스드 라이트", "en": "Mixed Light", "q": "mixed lighting photography" },
  { "id": "practical-lights", "ko": "프랙티컬 라이트", "en": "Practical Lights", "q": "practical lights photography" },
  { "id": "lens-flare", "ko": "렌즈 플레어", "en": "Lens Flare", "q": "lens flare photography" },
  { "id": "anamorphic", "ko": "아나모픽", "en": "Anamorphic Look", "q": "anamorphic lens photography look" },
  { "id": "tilt-shift", "ko": "틸트 시프트", "en": "Tilt-shift", "q": "tilt shift photography" },
  { "id": "miniature-effect", "ko": "미니어처 이펙트", "en": "Miniature Effect", "q": "miniature effect photography" },
  { "id": "grainy-film", "ko": "그레인/필름 그레인", "en": "Film Grain", "q": "film grain photography look" },
  { "id": "cross-processing", "ko": "크로스 프로세싱", "en": "Cross Processing", "q": "cross processed film look" },
  { "id": "desaturated", "ko": "저채도", "en": "Desaturated", "q": "desaturated color grading photography" },
  { "id": "high-saturation", "ko": "고채도", "en": "High Saturation", "q": "high saturation color grading photography" },
  { "id": "warm-tone", "ko": "웜 톤", "en": "Warm Tone", "q": "warm tone color grading photography" },
  { "id": "cool-tone", "ko": "쿨 톤", "en": "Cool Tone", "q": "cool tone color grading photography" }
];
