window.REFERENCE_KO_TITLE_MAP = {
  "Swiss Style": "스위스 스타일",
  "International Typographic Style": "국제 인쇄 스타일",
  "Bauhaus": "바우하우스",
  "Constructivism": "구성주의",
  "De Stijl": "데 스틸",
  "Ulm School Graphic": "울름 학교 그래픽",
  "Modernist Poster": "모더니스트 포스터",
  "Grid Poster": "그리드 포스터",
  "Typographic Poster": "인쇄상의 포스터",
  "Photo Typographic Poster": "사진 인쇄상의 포스터",
  "Art Deco": "아르데코",
  "Art Nouveau": "아르 누보",
  "Victorian Editorial": "빅토리아 사설",
  "Jugendstil Poster": "유겐트슈틸 포스터",
  "Vienna Secession Graphic": "비엔나 탈퇴 그래픽",
  "Neo Classical Poster": "네오 클래식 포스터",
  "Baroque Graphic": "바로크 그래픽",
  "Ukiyo E Graphic": "우키요 E 그래픽",
  "Woodcut Poster": "목판화 포스터",
  "Ornamental Lettering": "장식용 글자",
  "Risograph": "리소그래프",
  "Screen Print Poster": "스크린 인쇄 포스터",
  "Letterpress Editorial": "활판 인쇄 사설",
  "Halftone Print": "하프톤 인쇄",
  "Newsprint Collage": "신문 콜라주",
  "Linocut Graphic": "리노컷 그래픽",
  "Silkscreen Graphic": "실크스크린 그래픽",
  "Xerox Zine": "제록스 진",
  "Stencil Poster": "스텐실 포스터",
  "Monoprint Graphic": "모노프린트 그래픽",
  "Memphis": "멤피스",
  "New Wave Typography": "뉴 웨이브 타이포그래피",
  "Deconstructivist Graphic": "해체주의 그래픽",
  "Grunge Editorial": "그런지 사설",
  "Punk Zine": "펑크진",
  "Anti Design": "안티 디자인",
  "Maximalist Collage": "맥시멀리스트 콜라주",
  "Acid Graphics": "애시드 그래픽",
  "Psychedelic Poster": "사이키델릭 포스터",
  "Dada Montage": "다다 몽타주",
  "Y2K Web": "Y2K 웹",
  "Vaporwave": "증기파",
  "Synthwave Graphic": "신스웨이브 그래픽",
  "Cyberpunk HUD": "사이버펑크 HUD",
  "Retrofuturism": "레트로퓨처리즘",
  "Frutiger Aero": "프루티거 에어로",
  "Web 1.0": "웹 1.0",
  "Web 2.0 Glossy": "웹 2.0 광택",
  "Chrome Graphic": "크롬 그래픽",
  "Glitch Graphic": "글리치 그래픽",
  "Glassmorphism": "유리형태",
  "Neumorphism": "신경성",
  "Skeuomorphism": "스큐어모피즘",
  "Material Design": "머티리얼 디자인",
  "Fluent Design": "유창한 디자인",
  "Aqua UI": "아쿠아 UI",
  "Bento UI": "도시락 UI",
  "Soft UI": "소프트 UI",
  "Card UI": "카드 UI",
  "Dark Dashboard UI": "다크 대시보드 UI",
  "Data Dense Dashboard": "데이터 집약적 대시보드",
  "Minimal Dashboard": "최소한의 대시보드",
  "Card Based Dashboard": "카드 기반 대시보드",
  "Monochrome Dashboard": "흑백 대시보드",
  "Widget Dashboard": "위젯 대시보드",
  "Command Center UI": "명령 센터 UI",
  "Terminal Inspired UI": "터미널에서 영감을 받은 UI",
  "Table First Interface": "테이블 우선 인터페이스",
  "Chart First Interface": "차트 우선 인터페이스",
  "Control Panel UI": "제어판 UI",
  "Rounded Mobile UI": "둥근 모바일 UI",
  "Minimal Mobile UI": "최소한의 모바일 UI",
  "Gradient Mobile UI": "그라데이션 모바일 UI",
  "High Contrast Mobile UI": "고대비 모바일 UI",
  "Card Stack Mobile UI": "카드 스택 모바일 UI",
  "Pastel Mobile UI": "파스텔 모바일 UI",
  "Glass Mobile UI": "글래스 모바일 UI",
  "Brutalist Mobile UI": "브루탈리스트 모바일 UI",
  "Editorial Mobile UI": "편집 모바일 UI",
  "Floating Action Mobile UI": "플로팅 액션 모바일 UI",
  "Luxury Minimal Web": "럭셔리 미니멀 웹",
  "Editorial Commerce Web": "편집 커머스 웹",
  "Bold Campaign Landing": "대담한 캠페인 랜딩",
  "Image First Landing": "이미지 첫 번째 착륙",
  "Split Hero Landing": "스플릿 히어로 랜딩",
  "Monochrome Marketing Site": "흑백 마케팅 사이트",
  "Soft Gradient Landing": "부드러운 경사 계단참",
  "Brutalist Commerce Web": "잔혹한 상업 웹",
  "Magazine Style Landing": "매거진 스타일 랜딩",
  "High Contrast Brand Site": "고대비 브랜드 사이트",
  "Minimal Branding": "최소한의 브랜딩",
  "Luxury Branding": "럭셔리 브랜딩",
  "Playful Branding": "유쾌한 브랜딩",
  "Heritage Branding": "헤리티지 브랜딩",
  "Eco Branding": "에코 브랜딩",
  "Tech Branding": "기술 브랜딩",
  "Editorial Branding": "편집 브랜딩",
  "Packaging First Branding": "패키징 퍼스트 브랜딩",
  "Monogram Branding": "모노그램 브랜딩",
  "Mascot Branding": "마스코트 브랜딩",
  "Cosmetic Packaging": "화장품 포장",
  "Beverage Packaging": "음료 포장",
  "Coffee Packaging": "커피 포장",
  "Tea Packaging": "차 포장",
  "Skincare Packaging": "스킨케어 포장",
  "Snack Packaging": "스낵 포장",
  "Wine Label Design": "와인 라벨 디자인",
  "Craft Beer Packaging": "수제 맥주 포장",
  "Perfume Packaging": "향수 포장",
  "Sustainable Packaging": "지속 가능한 포장",
  "Magazine Grid Editorial": "매거진 그리드 사설",
  "Asymmetric Editorial Layout": "비대칭 편집 레이아웃",
  "Book Cover Typography": "책 표지 타이포그래피",
  "Album Cover Graphic": "앨범 표지 그래픽",
  "Lookbook Layout": "룩북 레이아웃",
  "Photo Book Layout": "사진첩 레이아웃",
  "Catalog Grid Layout": "카탈로그 그리드 레이아웃",
  "Annual Report Modern": "연례 보고서 현대",
  "Thesis Book Modern": "논문집 현대",
  "Portfolio Editorial Layout": "포트폴리오 편집 레이아웃",
  "Information Design": "정보디자인",
  "Infographic Design": "인포그래픽 디자인",
  "Data Visualization": "데이터 시각화",
  "Wayfinding System": "길찾기 시스템",
  "Iconography System": "도상학 시스템",
  "Pictogram System": "픽토그램 시스템",
  "Transit Map Design": "대중교통 지도 디자인",
  "Exhibition Signage": "전시 간판",
  "Diagram Design": "다이어그램 디자인",
  "Process Chart Design": "프로세스 차트 디자인",
  "Kinetic Typography": "키네틱 타이포그래피",
  "Title Sequence Design": "타이틀 시퀀스 디자인",
  "Broadcast Package": "방송 패키지",
  "Lower Third System": "로어서드 시스템",
  "Sports Broadcast Graphic": "스포츠 방송 그래픽",
  "News Broadcast Graphic": "뉴스 방송 그래픽",
  "Motion Poster": "모션 포스터",
  "Animated Explainer Graphic": "애니메이션 설명 그래픽",
  "UI Motion Design": "UI 모션 디자인",
  "Typographic Loop": "인쇄상의 루프",
  "Festival Poster": "축제 포스터",
  "Event Poster": "이벤트 포스터",
  "Typographic Campaign": "타이포그래피 캠페인",
  "Protest Poster": "항의 포스터",
  "Museum Poster": "박물관 포스터",
  "Concert Poster": "콘서트 포스터",
  "Film Poster Modern": "영화 포스터 현대",
  "Film Poster Minimal": "영화 포스터 미니멀",
  "Cultural Poster": "문화 포스터",
  "Exhibition Poster": "전시 포스터",
  "Flat Geometric Graphic": "평면 기하학적 그래픽",
  "Cut Paper Graphic": "컷 종이 그래픽",
  "3D Abstract Graphic": "3D 추상 그래픽",
  "Gradient Mesh Graphic": "그라디언트 메쉬 그래픽",
  "Isometric Illustration UI": "아이소메트릭 일러스트레이션 UI",
  "Doodle Branding": "기념일 로고 브랜딩",
  "Sticker Pack Graphic": "스티커 팩 그래픽",
  "Cartoon Editorial": "만화 사설",
  "Botanical Packaging Graphic": "식물 포장 그래픽",
  "Folk Pattern Graphic": "민속 패턴 그래픽",
  "Japanese Minimal": "일본식 미니멀",
  "Wabi Sabi": "와비사비",
  "Scandinavian Graphic": "스칸디나비아 그래픽",
  "Mid Century Modern": "미드 센추리 모던",
  "Brutalist Web": "잔혹한 웹",
  "Concrete Minimal": "콘크리트 최소",
  "Warm Minimal": "따뜻한 최소한의",
  "Luxury Interior Branding": "럭셔리 인테리어 브랜딩",
  "Spatial Signage": "공간 간판",
  "Architectural Diagram Style": "아키텍처 다이어그램 스타일",
  "Enterprise Design System": "엔터프라이즈 디자인 시스템",
  "Government Service Design": "정부 서비스 디자인",
  "Accessibility First UI": "접근성 우선 UI",
  "Design Token System": "디자인 토큰 시스템",
  "Component Library UI": "구성 요소 라이브러리 UI",
  "Documentation Site Design": "문서 사이트 디자인",
  "B2B Portal UI": "B2B 포털 UI",
  "Admin Console UI": "관리 콘솔 UI",
  "Workflow Builder UI": "워크플로 빌더 UI",
  "CRM Dashboard": "CRM 대시보드",
  "Immersive Storytelling Site": "몰입형 스토리텔링 사이트",
  "Parallax Editorial Web": "시차 편집 웹",
  "Split Screen Landing": "분할 화면 랜딩",
  "Scroll Narrative Web": "내러티브 웹 스크롤",
  "Cursor Reactive Web": "커서 반응형 웹",
  "Brutalist Editorial Web": "잔혹한 편집 웹",
  "Archive Website": "아카이브 웹사이트",
  "Portfolio Showcase": "포트폴리오 쇼케이스",
  "Gallery Microsite": "갤러리 마이크로사이트",
  "Interactive Timeline": "인터랙티브 타임라인",
  "Sci Fi Terminal UI": "공상 과학 터미널 UI",
  "Tactical Map UI": "전술 지도 UI",
  "Space Dashboard UI": "스페이스 대시보드 UI",
  "Mecha Control Panel": "메카 제어판",
  "Cyberpunk Shop UI": "사이버펑크 상점 UI",
  "Fantasy Game Menu": "판타지 게임 메뉴",
  "RPG Inventory UI": "RPG 인벤토리 UI",
  "Strategy HUD": "전략 HUD",
  "Retro Arcade Interface": "레트로 아케이드 인터페이스",
  "Holographic Panel": "홀로그램 패널",
  "Modern Anime": "현대 애니메이션",
  "Retro 80s Anime": "80년대 복고풍 애니메이션",
  "Retro 90s Anime": "90년대 복고풍 애니메이션",
  "Clean Anime": "깨끗한 애니메이션",
  "Painterly Anime": "회화적인 애니메이션",
  "Shonen Style": "소년 스타일",
  "Shojo Style": "쇼조 스타일",
  "Seinen Style": "세이넨 스타일",
  "Josei Style": "조세이 스타일",
  "Isekai Anime Style": "이세카이 애니메이션 스타일",
  "Manga Ink Line": "만화 잉크 라인",
  "Manga Screentone": "만화 스크린톤",
  "Gekiga Style": "게키가 스타일",
  "Sports Manga Style": "스포츠 만화 스타일",
  "Horror Manga Style": "공포 만화 스타일",
  "Comedy Manga Style": "코미디 만화 스타일",
  "Shoujo Lace Manga": "순조 레이스 만화",
  "Samurai Manga Style": "사무라이 만화 스타일",
  "Mecha Manga Style": "메카 만화 스타일",
  "Webtoon Clean": "웹툰클린",
  "Webtoon Rendered": "웹툰 렌더링",
  "Webtoon Minimal": "웹툰 미니멀",
  "Mobile Comic Style": "모바일 만화 스타일",
  "Romance Fantasy Webtoon": "로맨스 판타지 웹툰",
  "Action Webtoon Style": "액션 웹툰 스타일",
  "Thriller Webtoon Style": "스릴러 웹툰 스타일",
  "Slice of Life Webtoon": "삶의 조각 웹툰",
  "Color Comic Style": "컬러 만화 스타일",
  "Vertical Panel Character": "수직 패널 문자",
  "Korean Game Promo Character": "한국 게임 프로모션 캐릭터",
  "Chibi": "꼬마",
  "Super Deformed Hero": "슈퍼 변형 영웅",
  "Kawaii Mascot": "귀여운 마스코트",
  "Pastel Mascot": "파스텔 마스코트",
  "Round Blob Mascot": "둥근 물방울 마스코트",
  "Animal Mascot": "동물 마스코트",
  "Food Mascot": "음식 마스코트",
  "Tech Mascot": "기술 마스코트",
  "Kids App Mascot": "키즈 앱 마스코트",
  "Cozy Mascot": "아늑한 마스코트",
  "Classic Cartoon": "클래식 만화",
  "Rubber Hose": "고무 호스",
  "TV Animation Style": "TV 애니메이션 스타일",
  "Saturday Morning Cartoon": "토요일 아침 만화",
  "Flat Comedy Cartoon": "플랫 코미디 만화",
  "Adventure Cartoon": "모험 만화",
  "Silhouette Cartoon": "실루엣 만화",
  "Exaggerated Toon": "과장된 툰",
  "Family Cartoon": "가족 만화",
  "Sketchy Cartoon": "스케치 만화",
  "Ligne Claire": "라인 클레어",
  "Franco Belgian Comic": "프랑코 벨기에 만화",
  "Graphic Novel Minimal": "그래픽노블 미니멀",
  "Editorial Cartoon": "편집 만화",
  "Caricature Clean Line": "캐리커처 클린 라인",
  "Poster Cartoon Figure": "포스터 만화 그림",
  "Storybook Cartoon": "스토리북 만화",
  "Woodcut Character": "목판화 캐릭터",
  "Ink Wash Character": "잉크 워시 캐릭터",
  "Folk Tale Character": "민화 캐릭터",
  "American Comic": "미국 만화",
  "Superhero Modern": "슈퍼 히어로 모던",
  "Indie Comic Style": "인디 코믹 스타일",
  "Noir Comic Style": "느와르 만화 스타일",
  "Pulp Comic Hero": "펄프 코믹 히어로",
  "Sci Fi Comic Character": "공상 과학 만화 캐릭터",
  "Fantasy Comic Character": "판타지 만화 캐릭터",
  "Horror Comic Character": "공포 만화 캐릭터",
  "YA Graphic Novel Character": "YA 그래픽 소설 캐릭터",
  "Retro Silver Age Comic": "레트로 실버 에이지 만화",
  "Cel Shading": "셀 셰이딩",
  "Flat Vector Character": "평면 벡터 문자",
  "Gouache Character": "구아슈 캐릭터",
  "Watercolor Character": "수채화 캐릭터",
  "Marker Render Character": "마커 렌더 캐릭터",
  "Colored Pencil Character": "색연필 캐릭터",
  "Cut Paper Character": "컷 종이 캐릭터",
  "Screenprint Character": "스크린프린트 캐릭터",
  "Grainy Poster Character": "거친 포스터 캐릭터",
  "Minimal Shape Character": "최소 모양 문자",
  "Semi Realistic": "반현실적",
  "Painterly Character": "회화적 성격",
  "Realistic Ink Character": "현실적인 잉크 캐릭터",
  "Fantasy Illustration Character": "판타지 일러스트레이션 캐릭터",
  "Historical Illustration Character": "역사적 일러스트레이션 캐릭터",
  "Dark Fantasy Illustration": "다크 판타지 일러스트레이션",
  "Fashion Illustration Character": "패션 일러스트 캐릭터",
  "Romance Illustration Character": "로맨스 일러스트 캐릭터",
  "Storybook Illustration": "스토리북 일러스트레이션",
  "Childrens Book Character": "아동 도서 캐릭터",
  "Stylized 3D Character": "양식화된 3D 캐릭터",
  "Stylized Toy 3D": "양식화된 장난감 3D",
  "Mobile Game 3D Character": "모바일게임 3D 캐릭터",
  "Casual Game 3D Character": "캐주얼 게임 3D 캐릭터",
  "Hero Shooter 3D Character": "히어로 슈터 3D 캐릭터",
  "Family Animation 3D Character": "가족 애니메이션 3D 캐릭터",
  "Clay Look 3D Character": "클레이룩 3D 캐릭터",
  "Low Poly Character": "낮은 폴리 캐릭터",
  "Hand Painted 3D Character": "손으로 그린 ​​3D 캐릭터",
  "NPR 3D Character": "NPR 3D 캐릭터",
  "Realistic 3D Character": "현실적인 3D 캐릭터",
  "AAA Game Character": "AAA 게임 캐릭터",
  "Cinematic Hero Character": "시네마틱 영웅 캐릭터",
  "Tactical Realism Character": "전술적 현실주의 캐릭터",
  "Post Disaster Realism Character": "포스트 재난 현실주의 캐릭터",
  "Sci Fi Soldier Character": "공상 과학 군인 캐릭터",
  "Historical Warrior Character": "역사적인 전사 캐릭터",
  "Photoreal Character Bust": "포토리얼 캐릭터 흉상",
  "Grounded Civilian Character": "접지된 민간인 캐릭터",
  "Realistic Villain": "현실적인 악당",
  "Pixel Art Character": "픽셀 아트 캐릭터",
  "Chibi Pixel Sprite": "꼬마 픽셀 스프라이트",
  "JRPG Pixel Hero": "JRPG 픽셀 히어로",
  "Tactical RPG Sprite": "전술 RPG 스프라이트",
  "Fighting Game Sprite": "격투 게임 스프라이트",
  "Isometric Pixel Character": "아이소메트릭 픽셀 문자",
  "Monster Tamer Pixel": "몬스터 테이머 픽셀",
  "Cyberpunk Pixel Character": "사이버펑크 픽셀 캐릭터",
  "Fantasy NPC Pixel": "판타지 NPC 픽셀",
  "Cozy Game Pixel Character": "아늑한 게임 픽셀 캐릭터",
  "Creature Design": "생물 디자인",
  "Beast Character": "야수 캐릭터",
  "Insectoid Creature": "곤충형 ​​생물",
  "Aquatic Creature": "수생 생물",
  "Reptile Creature": "파충류 생물",
  "Birdlike Creature": "새 같은 생물",
  "Plant Creature": "식물 생물",
  "Elemental Creature": "원소 생물",
  "Mythic Beast": "신화적인 짐승",
  "Giant Monster": "거대 괴물",
  "Horror Creature": "공포 생물",
  "Undead Monster": "언데드 몬스터",
  "Cosmic Horror Monster": "우주 공포 괴물",
  "Demon Character": "악마 캐릭터",
  "Slasher Villain Design": "슬래셔 악당 디자인",
  "Gothic Monster": "고딕 몬스터",
  "Parasite Creature": "기생충 생물",
  "Mutation Monster": "돌연변이 몬스터",
  "Dark Fairy Monster": "다크페어리 몬스터",
  "Shadow Creature": "그림자 생물",
  "Mecha Character": "메카 캐릭터",
  "Super Robot": "슈퍼로봇",
  "Real Robot Pilot Suit": "실제 로봇 파일럿 슈트",
  "Android Character": "안드로이드 캐릭터",
  "Service Robot Mascot": "서비스 로봇 마스코트",
  "Military Mecha Pilot": "군용 메카 조종사",
  "Exosuit Character": "엑소슈트 캐릭터",
  "Sentinel Robot": "센티넬 로봇",
  "Retro Mecha Hero": "레트로 메카 히어로",
  "Mecha Girl": "메카 소녀",
  "Heroic Fantasy Character": "영웅적인 판타지 캐릭터",
  "Dark Fantasy Character": "다크 판타지 캐릭터",
  "High Fantasy Character": "하이 판타지 캐릭터",
  "Arcane Fantasy Character": "아케인 판타지 캐릭터",
  "Rogue Fantasy Character": "불량 판타지 캐릭터",
  "Gothic Fantasy Character": "고딕 판타지 캐릭터",
  "Noble Fantasy Character": "고귀한 판타지 캐릭터",
  "Barbarian Fantasy Style": "야만인 판타지 스타일",
  "Mythic Fantasy Character": "신화적인 판타지 캐릭터",
  "Nordic Fantasy Character": "북유럽 판타지 캐릭터",
  "Cyberpunk Character": "사이버펑크 캐릭터",
  "Retro Sci Fi Character": "복고풍 공상 과학 캐릭터",
  "Hard Surface Sci Fi Character": "단단한 표면 공상 과학 캐릭터",
  "Space Opera Character": "스페이스 오페라 캐릭터",
  "Android Character Style": "안드로이드 캐릭터 스타일",
  "Neon Street Fighter": "네온 스트리트 파이터",
  "Mech Pilot Character": "기계 조종사 캐릭터",
  "Corporate Dystopia Character": "기업 디스토피아 캐릭터",
  "Post Apocalyptic Character": "포스트 아포칼립스 캐릭터",
  "Biotech Character": "생명공학 캐릭터",
  "Samurai Character Style": "사무라이 캐릭터 스타일",
  "Ninja Character Style": "닌자 캐릭터 스타일",
  "Hanbok Character Style": "한복 캐릭터 스타일",
  "Victorian Character Style": "빅토리아 시대 캐릭터 스타일",
  "Rococo Character Style": "로코코 캐릭터 스타일",
  "Renaissance Character Style": "르네상스 캐릭터 스타일",
  "Ancient Egypt Character Style": "고대 이집트 캐릭터 스타일",
  "Mesoamerican Hero Style": "메소아메리카 영웅 스타일",
  "Arabian Nights Character Style": "아라비안 나이트 캐릭터 스타일",
  "Folklore Warrior Style": "민속 전사 스타일",
  "Turnaround Model Sheet": "턴어라운드 모델 시트",
  "Expression Sheet": "표현 시트",
  "Character Lineup": "캐릭터 라인업",
  "Costume Variation Sheet": "의상 변형 시트",
  "Prop Sheet Character": "소품 시트 캐릭터",
  "Silhouette Exploration": "실루엣 탐색",
  "Face Sheet": "페이스 시트",
  "Hair Variation Sheet": "헤어 바리에이션 시트",
  "Idle Pose Sheet": "유휴 포즈 시트",
  "Action Pose Sheet": "액션 포즈 시트",
  "NPC Style Sheet": "NPC 스타일 시트",
  "Boss Concept Character": "보스 컨셉 캐릭터",
  "Vtuber Avatar Style": "Vtuber 아바타 스타일",
  "Visual Novel Portrait Style": "비주얼 노벨 인물 스타일",
  "Gacha Splash Art Style": "가챠 스플래시 아트 스타일",
  "MOBA Hero Render": "MOBA 영웅 렌더링",
  "Fighting Game Intro Style": "격투 게임 소개 스타일",
  "Platformer Mascot Style": "플랫폼 게임 마스코트 스타일",
  "Cozy Sim Character Style": "아늑한 심 캐릭터 스타일",
  "Puzzle Mascot Style": "퍼즐 마스코트 스타일",
  "Natural Light Portrait": "자연광 인물 사진",
  "Studio Portrait": "스튜디오 초상화",
  "Environmental Portrait": "환경 초상화",
  "Candid Portrait": "솔직한 초상화",
  "Beauty Lighting": "뷰티 조명",
  "Editorial Fashion": "사설 패션",
  "Documentary Portrait": "다큐멘터리 초상화",
  "Corporate Portrait": "기업 초상화",
  "Actor Headshot": "배우 얼굴만",
  "Fine Art Portrait": "미술 초상화",
  "High Key": "하이 키",
  "Low Key": "로우 키",
  "Rembrandt Lighting": "렘브란트 조명",
  "Split Lighting": "분할 조명",
  "Butterfly Lighting": "나비 조명",
  "Loop Lighting": "루프 조명",
  "Clamshell Lighting": "클램셸 조명",
  "Broad Lighting": "넓은 조명",
  "Short Lighting": "짧은 조명",
  "Paramount Lighting": "파라마운트 조명",
  "Rim Light": "림 라이트",
  "Backlit": "백라이트",
  "Silhouette Portrait": "실루엣 초상화",
  "Chiaroscuro": "키아로스쿠로",
  "Noir Lighting": "느와르 조명",
  "Hard Flash Portrait": "하드 플래시 초상화",
  "Gel Lighting": "젤 조명",
  "Smoke Lit Portrait": "연기가 켜진 초상화",
  "Spotlight Portrait": "스포트라이트 초상화",
  "Window Light": "창문 조명",
  "Golden Hour": "골든 아워",
  "Blue Hour": "블루아워",
  "Noon Harsh Sun": "정오의 가혹한 태양",
  "Overcast Soft Light": "흐린 부드러운 빛",
  "Twilight Portrait": "황혼의 초상화",
  "Sunrise Landscape": "일출 풍경",
  "Sunset Silhouette": "일몰 실루엣",
  "Night Street": "밤의 거리",
  "Dawn Mist Photo": "새벽 안개 사진",
  "Moonlight Look": "달빛 룩",
  "Street Photography": "거리 사진",
  "Documentary Photography": "다큐멘터리 사진",
  "Photojournalism": "포토저널리즘",
  "Travel Documentary": "여행 다큐멘터리",
  "Urban Candid": "도시적인 솔직함",
  "Transit Photography": "대중교통 사진",
  "Market Photography": "시장 사진",
  "Protest Photography": "항의 사진",
  "Night Street Documentary": "밤거리 다큐멘터리",
  "Humanist Street": "인문주의 거리",
  "Lookbook Photography": "룩북 사진",
  "Runway Backstage": "런웨이 백스테이지",
  "Studio Fashion Editorial": "스튜디오 패션 사설",
  "Beauty Editorial": "뷰티 사설",
  "Luxury Campaign Photo": "럭셔리 캠페인 사진",
  "Minimal Fashion Catalog": "미니멀 패션 카탈로그",
  "Streetwear Editorial": "스트리트 사설",
  "Avant Garde Fashion": "아방가르드 패션",
  "Black White Fashion": "블랙 화이트 패션",
  "High Flash Fashion": "하이 플래시 패션",
  "Product Macro": "제품 매크로",
  "Still Life": "정물",
  "Minimal Product Photo": "최소한의 제품 사진",
  "Luxury Product Photo": "명품 사진",
  "Tech Product Photography": "기술 제품 사진",
  "Cosmetic Product Shot": "화장품 샷",
  "Watch Photography": "사진 감상",
  "Jewelry Photography": "주얼리 사진",
  "Beverage Product Photo": "음료 제품 사진",
  "Tabletop Product Photo": "탁상용 제품 사진",
  "Food Photography": "음식 사진",
  "Dark Food Photo": "어두운 음식 사진",
  "Bright Food Photo": "밝은 음식 사진",
  "Restaurant Editorial": "레스토랑 사설",
  "Beverage Splash Photo": "음료 스플래시 사진",
  "Dessert Close Up": "디저트 클로즈업",
  "Packaging With Food": "식품으로 포장",
  "Recipe Overhead": "레시피 오버헤드",
  "Rustic Table Food": "소박한 테이블 음식",
  "Commercial Drink Shot": "상업용 음료 샷",
  "Architecture Photography": "건축 사진",
  "Interior Photography": "인테리어 사진",
  "Real Estate Photography": "부동산 사진",
  "Hotel Interior Photo": "호텔 인테리어 사진",
  "Minimal Architecture": "최소한의 아키텍처",
  "Brutalist Architecture Photo": "잔혹한 건축 사진",
  "Modern House Photo": "현대 주택 사진",
  "Cafe Interior Photo": "카페 인테리어 사진",
  "Retail Space Photo": "리테일 공간 사진",
  "Symmetrical Architecture": "대칭 아키텍처",
  "Landscape Photography": "풍경 사진",
  "Seascape Photography": "바다 풍경 사진",
  "Forest Photography": "숲 사진",
  "Desert Landscape": "사막 풍경",
  "Mountain Photography": "산 사진",
  "Aerial Landscape": "공중 풍경",
  "Long Exposure Water": "장시간 노출 물",
  "Storm Landscape": "폭풍우 풍경",
  "Winter Landscape": "겨울 풍경",
  "Nature Macro": "자연 매크로",
  "Sports Photography": "스포츠 사진",
  "Dance Photography": "댄스 사진",
  "Fitness Photography": "피트니스 사진",
  "Motion Blur Action": "모션 블러 액션",
  "Freeze Motion Action": "모션 동작 정지",
  "Outdoor Adventure Photo": "야외 모험 사진",
  "Surf Photography": "서핑 사진",
  "Skate Photography": "스케이트 사진",
  "Martial Arts Photo": "무술 사진",
  "Concert Performance Photo": "콘서트 공연 사진",
  "Macro Photography": "매크로 사진",
  "Botanical Macro": "식물 매크로",
  "Insect Macro": "곤충 매크로",
  "Texture Study Photo": "텍스처 연구 사진",
  "Jewelry Macro": "쥬얼리 매크로",
  "Watch Detail Macro": "시계 세부정보 매크로",
  "Water Drop Macro": "물방울 매크로",
  "Fabric Detail Photo": "패브릭 디테일 사진",
  "Product Detail Shot": "제품 상세 샷",
  "Scientific Macro": "과학적인 매크로",
  "Film Look": "필름 룩",
  "Portra Tone": "포트라톤",
  "Cinestill": "시네스틸",
  "Kodachrome Look": "코다크롬 룩",
  "Fuji Provia Look": "후지 프로비아 룩",
  "Fuji Velvia Look": "후지 벨비아 룩",
  "Ektachrome Look": "엑타크롬 룩",
  "Matte Color": "무광택 색상",
  "Teal Orange": "청록 오렌지",
  "Muted Tone": "음소거 톤",
  "Black White High Contrast": "검정색 흰색 고대비",
  "Black White Soft Range": "블랙 화이트 소프트 레인지",
  "Infrared": "적외선",
  "Monochrome Minimal": "흑백 최소",
  "Graphic Shadow Photo": "그래픽 그림자 사진",
  "Silhouette Graphic": "실루엣 그래픽",
  "Grainy Monochrome": "거친 단색",
  "Silver Gelatin Look": "실버 젤라틴 룩",
  "Noir Monochrome": "느와르 흑백",
  "Architecture Monochrome": "건축 흑백",
  "Double Exposure": "이중 노출",
  "Prism Photography": "프리즘 사진",
  "Lens Flare Portrait": "렌즈 플레어 인물 사진",
  "Intentional Motion Blur": "의도적인 모션 블러",
  "Long Exposure Light Trails": "장노출 라이트 트레일",
  "Cyanotype Inspired Photo": "Cyanotype에서 영감을 받은 사진",
  "Wet Plate Look": "웨트 플레이트 룩",
  "Cross Process Look": "크로스 프로세스 룩",
  "Solarized Photo": "태양광 사진",
  "Lomo Snapshot": "로모 스냅샷",
  "Symmetry Photography": "대칭 사진",
  "Leading Lines Photo": "리딩라인 사진",
  "Negative Space Photo": "네거티브 스페이스 사진",
  "Reflection Photography": "반사 사진",
  "Frame Within Frame": "프레임 안의 프레임",
  "Overhead Flat Lay": "오버헤드 플랫 레이",
  "Top Down Still Life": "하향식 정물",
  "Off Center Composition": "오프 센터 구성",
  "Tight Crop Portrait": "타이트 크롭 인물 사진",
  "Wide Environmental Frame": "넓은 환경 프레임",
  "35mm Documentary Look": "35mm 다큐멘터리 룩",
  "50mm Natural View": "50mm 내추럴 뷰",
  "85mm Portrait Compression": "85mm 인물 압축",
  "Wide Angle Portrait": "광각 인물 사진",
  "Telephoto Street Look": "망원 스트리트 룩",
  "Shallow Depth Portrait": "얕은 깊이 인물 사진",
  "Deep Focus Environmental": "딥 포커스 환경",
  "Tilt Shift Cityscape": "틸트 시프트 도시 풍경",
  "Fisheye Experimental": "피쉬아이 실험",
  "Macro Bokeh": "매크로 보케",
  "Neon Night": "네온 나이트",
  "Rainy Night Street": "비오는 밤의 거리",
  "Gas Station At Night": "밤에 주유소",
  "Cyberpunk Alley Photo": "사이버펑크 골목 사진",
  "City Lights Bokeh": "도시의 불빛 보케",
  "Car Light Trails": "자동차 라이트 트레일",
  "Blue Neon Portrait": "블루 네온 초상화",
  "Red Gel Night Portrait": "레드 젤 나이트 인물",
  "Club Photography": "클럽 사진",
  "Concert Lighting Photo": "콘서트 조명 사진",
  "Wedding Editorial": "결혼식 사설",
  "Wedding Documentary": "웨딩 다큐멘터리",
  "Ceremony Candid": "솔직한 시상식",
  "Reception Flash Style": "리셉션 플래시 스타일",
  "Event Photojournalism": "이벤트 포토저널리즘",
  "Festival Documentary": "페스티벌 다큐멘터리",
  "Corporate Event Candid": "기업 행사 솔직함",
  "Family Lifestyle Session": "가족 라이프스타일 세션",
  "Graduation Portrait Style": "졸업 초상화 스타일",
  "Couple Lifestyle Session": "커플 라이프스타일 세션",
  "Travel Photography": "여행 사진",
  "Cultural Portrait": "문화 초상화",
  "Market Travel Photo": "시장 여행 사진",
  "Temple Photography": "성전 사진",
  "Coastal Town Travel": "해안 마을 여행",
  "Train Window Travel": "기차 창구 여행",
  "Desert Nomad Portrait": "사막 유목민 초상화",
  "Rural Documentary": "농촌 다큐멘터리",
  "Festival Travel Photo": "축제 여행 사진",
  "Heritage Architecture Travel": "문화유산 건축 여행",
  "Wes Anderson": "웨스 앤더슨",
  "David Fincher": "데이비드 핀처",
  "Denis Villeneuve": "드니 빌뇌브",
  "Sofia Coppola": "소피아 코폴라",
  "Spike Jonze": "스파이크 존즈",
  "Greta Gerwig": "그레타 거윅",
  "Barry Jenkins": "배리 젠킨스",
  "Christopher Nolan": "크리스토퍼 놀란",
  "Michael Mann": "마이클 만",
  "Steven Spielberg": "스티븐 스필버그",
  "Wong Kar Wai": "왕가와이",
  "Park Chan Wook": "박찬욱",
  "Akira Kurosawa": "구로사와 아키라",
  "Hirokazu Koreeda": "고레에다 히로카즈",
  "Edward Yang": "에드워드 양",
  "Zhang Yimou": "장이머우",
  "Bong Joon Ho": "봉준호",
  "Shunji Iwai": "이와이 슌지",
  "Hou Hsiao Hsien": "허우샤오시엔",
  "Lee Chang Dong": "이창동",
  "Stanley Kubrick": "스탠리 큐브릭",
  "Andrei Tarkovsky": "안드레이 타르코프스키",
  "Jean Luc Godard": "장 뤽 고다르",
  "Federico Fellini": "페데리코 펠리니",
  "Ingmar Bergman": "잉마르 베리만",
  "Michelangelo Antonioni": "미켈란젤로 안토니오니",
  "Pedro Almodovar": "페드로 알모도바르",
  "Lars von Trier": "라스 폰 트리어",
  "Wim Wenders": "빔 벤더스",
  "Jacques Demy": "자크 데미",
  "Guillermo del Toro": "기예르모 델 토로",
  "Tim Burton": "팀 버튼",
  "Ridley Scott": "리들리 스콧",
  "Tony Scott": "토니 스캇",
  "Nicolas Winding Refn": "니콜라스 윈딩 레픈",
  "Gaspar Noe": "가스파 노에",
  "Dario Argento": "다리오 아르젠토",
  "John Carpenter": "존 카펜터",
  "Brian De Palma": "브라이언 드 팔마",
  "George Miller": "조지 밀러",
  "Annie Leibovitz": "애니 레보비츠",
  "Helmut Newton": "헬무트 뉴턴",
  "Irving Penn": "어빙 펜",
  "Richard Avedon": "리차드 아베돈",
  "Peter Lindbergh": "피터 린드버그",
  "Tim Walker": "팀 워커",
  "Paolo Roversi": "파올로 로베르시",
  "Steven Meisel": "스티븐 마이젤",
  "Ellen von Unwerth": "엘렌 폰 운워스",
  "Nick Knight": "닉 나이트",
  "Steve McCurry": "스티브 맥커리",
  "Saul Leiter": "사울 라이터",
  "Daido Moriyama": "모리야마 다이도",
  "Fan Ho": "판호",
  "Henri Cartier Bresson": "앙리 카르티에 브레송",
  "Vivian Maier": "비비안 마이어",
  "Garry Winogrand": "게리 위노그랜드",
  "Josef Koudelka": "요세프 쿠델카",
  "Alex Webb": "알렉스 웹",
  "William Eggleston": "윌리엄 이글스턴",
  "Gregory Crewdson": "그레고리 크루드슨",
  "Cindy Sherman": "신디 셔먼",
  "Andreas Gursky": "안드레아스 구르스키",
  "Jeff Wall": "제프 월",
  "Nan Goldin": "낸 골딘",
  "Sally Mann": "샐리 만",
  "Alec Soth": "알렉 소스",
  "Hiroshi Sugimoto": "스기모토 히로시",
  "Wolfgang Tillmans": "볼프강 틸만스",
  "Rinko Kawauchi": "카와우치 린코",
  "Sebastiao Salgado": "세바스티앙 살가도",
  "Martin Parr": "마틴 파",
  "Lee Jeffries": "리 제프리스",
  "Jimmy Nelson": "지미 넬슨",
  "Steve Winter": "스티브 윈터",
  "Gregory Colbert": "그레고리 콜버트",
  "Trent Parke": "트렌트 파크",
  "Raghu Rai": "라구 라이",
  "Cristina Mittermeier": "크리스티나 미터마이어",
  "Platon": "플라톤",
  "Hayao Miyazaki": "미야자키 하야오",
  "Satoshi Kon": "콘 사토시",
  "Yoshitaka Amano": "아마노 요시타카",
  "Katsuhiro Otomo": "오토모 카츠히로",
  "Osamu Tezuka": "데즈카 오사무",
  "Takehiko Inoue": "이노우에 다케히코",
  "Naoko Takeuchi": "타케우치 나오코",
  "Rumiko Takahashi": "다카하시 루미코",
  "CLAMP": "집게",
  "Tite Kubo": "쿠보 타이트",
  "Moebius": "뫼비우스",
  "Herge": "헤르게",
  "Enki Bilal": "엔키 빌랄",
  "Milo Manara": "마일로 마나라",
  "Hugo Pratt": "휴고 프랫",
  "Lorenzo Mattotti": "로렌조 마토티",
  "Joann Sfar": "조앤 스파",
  "Claire Wendling": "클레어 웬들링",
  "Nicolas de Crecy": "니콜라스 드 크레시",
  "Benjamin Lacombe": "벤자민 라콤",
  "Mary Blair": "메리 블레어",
  "Eyvind Earle": "에이빈드 얼",
  "Glen Keane": "글렌 킨",
  "Genndy Tartakovsky": "겐디 타르타코프스키",
  "Rebecca Sugar": "레베카 슈가",
  "Don Bluth": "돈 블루스",
  "Tomm Moore": "톰 무어",
  "Chris Sanders": "크리스 샌더스",
  "Tadahiro Uesugi": "우에스기 타다히로",
  "Frederic Back": "프레데릭 백",
  "Craig Mullins": "크레이그 멀린스",
  "Syd Mead": "시드 미드",
  "Feng Zhu": "펑주",
  "Jama Jurabaev": "자마 주라바예프",
  "Maciej Kuciara": "마치에이 쿠치아라",
  "Raphael Lacoste": "라파엘 라코스테",
  "Claire Hummel": "클레어 험멜",
  "Ian McQue": "이안 맥큐",
  "Ruan Jia": "지아 루안",
  "James Gurney": "제임스 거니",
  "Quentin Blake": "쿠엔틴 블레이크",
  "Beatrix Potter": "베아트릭스 포터",
  "Maurice Sendak": "모리스 센닥",
  "Tove Jansson": "토베 얀손",
  "Shaun Tan": "숀 탄",
  "Eric Carle": "에릭 칼",
  "Oliver Jeffers": "올리버 제퍼스",
  "Kay Nielsen": "케이 닐슨",
  "Arthur Rackham": "아서 래컴",
  "Maira Kalman": "마이라 칼만",
  "Caravaggio": "카라바조",
  "Leonardo da Vinci": "레오나르도 다 빈치",
  "Michelangelo": "미켈란젤로",
  "Raphael": "라파엘",
  "Titian": "티치아노",
  "Rembrandt": "렘브란트",
  "Vermeer": "베르메르",
  "Velazquez": "벨라스케스",
  "Peter Paul Rubens": "피터 폴 루벤스",
  "El Greco": "엘 그레코",
  "Claude Monet": "클로드 모네",
  "Edgar Degas": "에드가 드가",
  "Pierre Auguste Renoir": "피에르 오귀스트 르누아르",
  "Vincent van Gogh": "빈센트 반 고흐",
  "Paul Cezanne": "폴 세잔",
  "Henri de Toulouse Lautrec": "앙리 드 툴루즈 로트렉",
  "Georges Seurat": "조르주 쇠라",
  "Paul Gauguin": "폴 고갱",
  "Berthe Morisot": "베르트 모리조",
  "Mary Cassatt": "메리 카사트",
  "Gustav Klimt": "구스타프 클림트",
  "Egon Schiele": "에곤 쉴레",
  "Rene Magritte": "르네 마그리트",
  "Salvador Dali": "살바도르 달리",
  "Pablo Picasso": "파블로 피카소",
  "Henri Matisse": "앙리 마티스",
  "Joan Miro": "호안 미로",
  "Wassily Kandinsky": "바실리 칸딘스키",
  "Paul Klee": "폴 클레",
  "Giorgio de Chirico": "조르조 데 키리코",
  "Edward Hopper": "에드워드 호퍼",
  "Georgia OKeeffe": "조지아 오키프",
  "Jean Michel Basquiat": "장 미셸 바스키아",
  "Keith Haring": "키스 해링",
  "Mark Rothko": "마크 로스코",
  "David Hockney": "데이비드 호크니",
  "Frida Kahlo": "프리다 칼로",
  "Diego Rivera": "디에고 리베라",
  "Tamara de Lempicka": "타마라 드 렘피카",
  "Yoshitomo Nara": "나라 요시토모",
  "Saul Bass": "사울 배스",
  "Paul Rand": "폴 랜드",
  "Massimo Vignelli": "마시모 비넬리",
  "Josef Muller Brockmann": "요제프 뮐러 브로크만",
  "Paula Scher": "폴라 셰어",
  "David Carson": "데이비드 카슨",
  "Neville Brody": "네빌 브로디",
  "Milton Glaser": "밀턴 글레이저",
  "Shigeo Fukuda": "후쿠다 시게오",
  "Ikko Tanaka": "다나카 잇코",
  "Peter Saville": "피터 사빌",
  "Alan Fletcher": "앨런 플레처",
  "Stefan Sagmeister": "스테판 사그마이스터",
  "April Greiman": "에이프릴 그레이먼",
  "Wolfgang Weingart": "볼프강 바인가르트",
  "Herb Lubalin": "허브 루발린",
  "Otl Aicher": "오틀 아이허",
  "Muriel Cooper": "뮤리엘 쿠퍼",
  "Susan Kare": "수잔 케어",
  "Tadanori Yokoo": "요코 타다노리",
  "Beeple": "비플",
  "Loish": "로이시",
  "Kim Jung Gi": "김정기",
  "Takashi Murakami": "무라카미 다카시",
  "James Jean": "제임스 진",
  "Hajime Sorayama": "소라야마 하지메",
  "Junji Ito": "이토 준지",
  "Krenz Cushart": "크렌츠 쿠샤르트",
  "Norman Rockwell": "노먼 록웰",
  "Ashley Wood": "애슐리 우드"
};
